### ISSUE TITLE
Three Wire SPI - Software Clock Strobe

### ISSUE THREAD

**Issue by iBrajinovic** [iBrajinovic/avr#7]
In the SPI example the clock was generated manually by toggling the output pin and not by using the ``USICLK: Clock Strobe`` bit of the ``USICR - USI Control Register``. Is that not supposed to be like that or is this bit only for the internal counter relevant?

**Comment by ghost** [comment]
> Writing a one to this bit location strobes the USI Data Register to shift one step and the counter to increment by
> one, provided that the software clock strobe option has been selected by writing USICS[1:0] bits to zero

So... the function of the ``USICLK`` is to increment the counter and to shift the data inside the data register. 

The question I am asking myself now is, how did I manage to transmit 0xAA a week before by only toggling the output signal pin???

**Comment by Brajinovic** [comment]
**USICR - The USI Control Register**
The ``USICLK`` does the shifting of the Data Register and the counter incrementing
The ``USITC`` does the Output Pin manipulation
From my current understanding I should use both of them but... it worked by manually writing to the SCK Pin, without the use of the ``USICR``. How and why I do not know!
